package com.i46.management.controller;

import com.i46.management.model.AccountDTO;
import com.i46.management.model.LoginDTO;
import com.i46.management.model.entity.*;
import com.i46.management.model.service.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.sql.Timestamp;
import java.util.*;

@RestController
public class AuthController {
    private static final Logger logger = LoggerFactory.getLogger(AuthController.class);

    @Autowired
    AccountService accountService;

    @Autowired
    TransactionService transactionService;

    @Autowired
    private TokenService tokenService;

    @Autowired
    private CreditService creditService;

    @Autowired
    private ContactService contactService;

    @Value("${app.credit.init}")
    private Integer INIT_CREDIT;

    @Value("${app.credit.transaction}")
    private Integer TRANSACTION_CREDIT;


    @GetMapping("/welcome")
    public String welcome() {
        return "User authenticated.";
    }


    @PostMapping("/login")
    public ResponseEntity<Map<String, Object>> login(@RequestBody LoginDTO loginDTO) {
        return null;
    }

    @PostMapping("/account")
    public ResponseEntity<Map<String, Object>> createAccount(@RequestBody AccountDTO accountDTO) {
        Map<String, Object> response = new HashMap<>();
        if (accountDTO.getAppId() != null && accountService.isAppIdExists(accountDTO.getAppId())) {
            Optional<Account> accountExisting = accountService.getByAppId(accountDTO.getAppId());
            if (accountExisting.isPresent()) {
                response.put("data", accountExisting.get());
                return new ResponseEntity<>(response, HttpStatus.OK);
            }
        } else {
            if (accountDTO.getName() == null || accountDTO.getName().isEmpty()) {
                response.put("error", "Name is required");
                return new ResponseEntity<>(response, HttpStatus.BAD_REQUEST);
            }
            if (accountDTO.getChannel() == null || accountDTO.getChannel().isEmpty()) {
                response.put("error", "Channel is required");
                return new ResponseEntity<>(response, HttpStatus.BAD_REQUEST);
            }
            if (accountDTO.getDescription() == null || accountDTO.getDescription().isEmpty()) {
                response.put("error", "Description is required");
                return new ResponseEntity<>(response, HttpStatus.BAD_REQUEST);
            }


            Calendar cal = Calendar.getInstance();
            Timestamp timestamp = new Timestamp(cal.getTimeInMillis());
            accountDTO.setCreatedAt(timestamp);

            int init = INIT_CREDIT;
            if (accountDTO.getCreatedBy() == null) {
                accountDTO.setActive(true);
                accountDTO.setActivatedAt(timestamp);
            } else {
                accountDTO.setActive(false);
                init = TRANSACTION_CREDIT;
            }

            Account account = new Account(accountDTO);
            Account accountSave = accountService.save(account, init);

            int totalCredit = TRANSACTION_CREDIT * 2;
            if (accountSave != null) {

                //create otp token
                Token otp = new Token(accountSave.getId(), TokenType.ONE_TIME_KEYS.getId(), "init",
                        "autogenerated", timestamp, AccessType.WRITE_ONCE_READ_MANY.getId(), null);
                Token otpSave = tokenService.save(otp);
                //add transaction to creator - negative type
                Transaction otpTransact = new Transaction(accountSave.getId(), 0, otpSave.getId(), TransactionType.POSITIVE.name(), "new account", null, timestamp);
                transactionService.save(otpTransact);

                if (accountSave.getCreatedBy() != null) {
                    Optional<Account> accountInviter = accountService.getById(account.getCreatedBy());

                    if (accountInviter.isPresent()) {
                        Account accountContactSave = contactService.save(accountSave, account.getCreatedBy());
                        if (accountContactSave != null) {
                            Account accountInviterSave = contactService.save(accountInviter.get(), accountSave.getId());
                            if (accountInviterSave != null) {
                                //check if creator has credits left
                                int creditAvailable = creditService.getCredit(accountSave.getCreatedBy());
                                if (creditAvailable >= totalCredit) {
                                    //create token
                                    List<UUID> accessUsers = new ArrayList<>();
                                    accessUsers.add(accountSave.getId());
                                    Token token = new Token(accountSave.getId(), TokenType.NEW_USER_ACCOUNT.getId(), accountSave.getName(), accountSave.getDescription(), timestamp, AccessType.WRITE_ONCE_READ_ONCE.getId(), accessUsers);
                                    Token tokenSave = tokenService.save(token);

                                    //add transaction to creator - negative type
                                    Transaction transaction = new Transaction(accountSave.getCreatedBy(), totalCredit, tokenSave.getId(), TransactionType.NEGATIVE.name(), "minus credit for creating new account", null, timestamp);
                                    transactionService.save(transaction, creditAvailable);

                                    response.put("data", accountContactSave);
                                    return new ResponseEntity<>(response, HttpStatus.CREATED);
                                }
                            }
                        }
                    }
                } else {
                    response.put("data", accountSave);
                    return new ResponseEntity<>(response, HttpStatus.CREATED);
                }

            }

        }

        response.put("error", "An unexpected error occurred");
        return new ResponseEntity<>(response, HttpStatus.INTERNAL_SERVER_ERROR);

    }


}